sudo: required
language: node_js
node_js:
  - stable
services:
  - docker
  - npm
os:
  - linux
env:
  global:
    - DOCKER_IMAGE_NAME="frontend-project"
    - DOCKER_HUB_ORG="agatharach"
before_script:
  - openssl aes-256-cbc -K $encrypted_36ba49b2dc0a_key -iv $encrypted_36ba49b2dc0a_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
  - sudo chmod +x deploy.sh
  - sudo chmod 600 deploy_rsa
  - CI=false npm run build
after_script:
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  - docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
    .
  - docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
  - docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
    ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}" && docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:latest
  - ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
  - ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR 'bash -s' < deploy.sh
before_install:
